create table if not exists public.gdo_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  role text not null check (role in ('franchisee', 'developer', 'admin')),
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.gdo_cases (
  id bigint generated by default as identity primary key,
  owner_user_id bigint not null references public.gdo_users(id),
  developer_user_id bigint references public.gdo_users(id),
  title text not null,
  business_type text not null check (business_type in ('炸雞', '火鍋', '燒烤', '便當')),
  county text not null default '',
  status text not null default 'draft'
    check (status in ('draft', 'submitted', 'needs_info', 'evaluating', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gdo_candidates (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.gdo_cases(id) on delete cascade,
  address text not null,
  monthly_rent bigint,
  area_ping double precision,
  report_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gdo_report_versions (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.gdo_candidates(id) on delete cascade,
  version_number integer not null,
  report_json jsonb not null,
  created_at timestamptz not null default now(),
  unique (candidate_id, version_number)
);

create table if not exists public.gdo_surveys (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.gdo_candidates(id) on delete cascade,
  user_id bigint not null references public.gdo_users(id),
  onsite_count integer,
  notes text not null default '',
  photo_data jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.gdo_case_comments (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.gdo_cases(id) on delete cascade,
  user_id bigint not null references public.gdo_users(id),
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.gdo_notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.gdo_users(id) on delete cascade,
  case_id bigint references public.gdo_cases(id) on delete cascade,
  event_type text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists gdo_cases_owner_idx
  on public.gdo_cases(owner_user_id, updated_at desc);
create index if not exists gdo_cases_developer_idx
  on public.gdo_cases(developer_user_id, updated_at desc);
create index if not exists gdo_candidates_case_idx
  on public.gdo_candidates(case_id, created_at);
create index if not exists gdo_report_versions_candidate_idx
  on public.gdo_report_versions(candidate_id, version_number desc);
create index if not exists gdo_surveys_candidate_idx
  on public.gdo_surveys(candidate_id, created_at desc);
create index if not exists gdo_comments_case_idx
  on public.gdo_case_comments(case_id, created_at);
create index if not exists gdo_notifications_user_idx
  on public.gdo_notifications(user_id, created_at desc);

alter table public.gdo_users enable row level security;
alter table public.gdo_cases enable row level security;
alter table public.gdo_candidates enable row level security;
alter table public.gdo_report_versions enable row level security;
alter table public.gdo_surveys enable row level security;
alter table public.gdo_case_comments enable row level security;
alter table public.gdo_notifications enable row level security;

revoke all on table public.gdo_users from anon, authenticated;
revoke all on table public.gdo_cases from anon, authenticated;
revoke all on table public.gdo_candidates from anon, authenticated;
revoke all on table public.gdo_report_versions from anon, authenticated;
revoke all on table public.gdo_surveys from anon, authenticated;
revoke all on table public.gdo_case_comments from anon, authenticated;
revoke all on table public.gdo_notifications from anon, authenticated;

grant usage on schema public to service_role;
grant all on table public.gdo_users to service_role;
grant all on table public.gdo_cases to service_role;
grant all on table public.gdo_candidates to service_role;
grant all on table public.gdo_report_versions to service_role;
grant all on table public.gdo_surveys to service_role;
grant all on table public.gdo_case_comments to service_role;
grant all on table public.gdo_notifications to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'gdo-surveys',
  'gdo-surveys',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

comment on table public.gdo_users is 'GDO isolated workspace users; accessed only by the trusted Render backend.';
comment on table public.gdo_cases is 'GDO site-selection cases.';
comment on table public.gdo_candidates is 'Candidate storefronts and current report snapshots.';
comment on table public.gdo_report_versions is 'Immutable GDO report version history.';
